pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Ornithe Releases'
			url = 'https://maven.ornithemc.net/releases'
		}
		maven {
			name = 'Ornithe Snapshots'
			url = 'https://maven.ornithemc.net/snapshots'
		}
		maven {
			name = "Legacy Fabric"
			url = "https://maven.legacyfabric.net/"
		}
		mavenLocal()
		gradlePluginPortal()
	}
}
